name: Publish Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine toml
        
    - name: Extract package names and versions
      id: extract-packages
      run: |
        import toml
        with open("pyproject.toml") as f:
            pyproject = toml.load(f)
        requires = pyproject["build-system"]["requires"]
        package_list = " ".join(requires)
        print(f"::set-output name=packages::{package_list}")
      shell: python

    - name: Install build dependencies
      run: |
        pip install ${{ steps.extract-packages.outputs.packages }}    

    - name: Build package
      run: python setup.py sdist

    - name: Publish package to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload --repository-url https://upload.pypi.org/legacy/ --username __token__ --password "${PYPI_API_TOKEN}" dist/*
